# Generated by Django 6.0.4 on 2026-05-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cor_fundo', models.CharField(default='#FFFFFF', max_length=7)),
                ('tipo_layout', models.CharField(default='TEXTO', max_length=20)),
            ],
            options={
                'db_table': 'anotacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#3498DB', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'etiquetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnotacaoEtiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('anotacao', models.ForeignKey(db_column='anotacao_id', on_delete=django.db.models.deletion.CASCADE, to='core.anotacoes')),
                ('etiqueta', models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, to='core.etiquetas')),
            ],
            options={
                'db_table': 'anotacao_etiquetas',
                'managed': True,
                'unique_together': {('anotacao', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='ElementosVisuais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_forma', models.CharField(max_length=30)),
                ('texto_interno', models.TextField(blank=True, null=True)),
                ('posicao_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('posicao_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, default=80.0, max_digits=10)),
                ('cor_preenchimento', models.CharField(default='#FFFFFF', max_length=7)),
                ('cor_borda', models.CharField(default='#000000', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('anotacao', models.ForeignKey(db_column='anotacao_id', on_delete=django.db.models.deletion.CASCADE, to='core.anotacoes')),
            ],
            options={
                'db_table': 'elementos_visuais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConexoesLinhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linha', models.CharField(default='RETA', max_length=20)),
                ('cor_linha', models.CharField(default='#000000', max_length=7)),
                ('espessura', models.IntegerField(blank=True, default=2, null=True)),
                ('texto_rotulo', models.CharField(blank=True, max_length=50, null=True)),
                ('anotacao', models.ForeignKey(db_column='anotacao_id', on_delete=django.db.models.deletion.CASCADE, to='core.anotacoes')),
                ('elemento_destino', models.ForeignKey(db_column='elemento_destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='core.elementosvisuais')),
                ('elemento_origem', models.ForeignKey(db_column='elemento_origem_id', on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='core.elementosvisuais')),
            ],
            options={
                'db_table': 'conexoes_linhas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='anotacoes',
            name='etiquetas',
            field=models.ManyToManyField(through='core.AnotacaoEtiquetas', to='core.etiquetas'),
        ),
        migrations.AddField(
            model_name='etiquetas',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios'),
        ),
        migrations.AddField(
            model_name='anotacoes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios'),
        ),
        migrations.AlterUniqueTogether(
            name='etiquetas',
            unique_together={('usuario', 'nome')},
        ),
    ]
