# Generated by Django 6.0.4 on 2026-06-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anotacoes',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios'),
        ),
    ]
