# Generated by Django 6.0.4 on 2026-06-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anotacoes_importante_alter_anotacoes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='data_prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anotacoes',
            name='dias_antecedencia_alerta',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('anotacao', models.ForeignKey(db_column='anotacao_id', on_delete=django.db.models.deletion.CASCADE, to='core.anotacoes')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'notificacoes',
                'managed': True,
            },
        ),
    ]
