# Generated by Django 6.0.4 on 2026-06-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anotacoes_data_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='anotacao',
            field=models.ForeignKey(blank=True, db_column='anotacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.anotacoes'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('LEMBRETE', 'Lembrete'), ('REUNIAO', 'Reunião'), ('EVENTO', 'Evento'), ('ANIVERSARIO', 'Aniversário'), ('AVALIACAO', 'Avaliação')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'eventos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notificacoes',
            name='evento',
            field=models.ForeignKey(blank=True, db_column='evento_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventos'),
        ),
        migrations.AddIndex(
            model_name='eventos',
            index=models.Index(fields=['data_inicio'], name='idx_evento_data_inicio'),
        ),
    ]
