# Generated by Django 6.0.4 on 2026-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notificacoes_anotacao_eventos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='diretorio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
