# Generated by Django 6.0.4 on 2026-06-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_anotacoes_diretorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
