# Generated by Django 6.0.4 on 2026-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anotacoes_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
